### ISSUE TITLE
 Error resolving type specified in JSON 'DotNetCheck.Manifest.NuGetFeedVariableMapper, MauiCheck'. Path 'check.variableMappers[0].$type', line 9, position 74.

### ISSUE THREAD

**Issue by qcjxberin** [Redth/dotnet-maui-check#107]
Error resolving type specified in JSON 'DotNetCheck.Manifest.NuGetFeedVariableMapper, MauiCheck'. Path
'check.variableMappers[0].$type', line 9, position 74.

![image](https://user-images.githubusercontent.com/5792218/129586679-749d1aa6-241c-4657-95a0-bbb2b7ecb73c.png)

**Comment by takaz-ams** [comment]
Getting same error

![image](https://user-images.githubusercontent.com/54239149/129749603-df9e75a3-148a-4a87-b781-3e1c026d72f7.png)

**Comment by bddckr** [comment]
You are running an old version of this tool. Try again after updating maui-check first via
```
dotnet tool update -g redth.net.maui.check
```

**Comment by fpenbegul** [comment]
> You are running an old version of this tool. Try again after updating maui-check first via
> 
> ```
> dotnet tool update -g redth.net.maui.check
> ```

I was have same issue for days. 
My problem was solved with Visual Studio upgrade. I hope others solved the problem too. Thanks. 



![image](https://user-images.githubusercontent.com/18633771/129781454-f983ae41-ae8b-4c42-a07a-df2e1e08f576.png)

**Comment by alexeystrakh** [comment]
Same here, upgrade helps
