### ISSUE TITLE
The requested name is valid, but data for the requested type cannot be found.

### ISSUE THREAD

**Issue by sharpwood** [Redth/dotnet-maui-check#12]
? Synchronizing configuration...
Error: The requested name is valid, but data for the requested type cannot be found.

I used ctrl+c break it when it is downloading .net sdk 6 preview 3 , and then run it again. It looks like have some problem.

**Comment by sharpwood** [comment]
It's because this address is inaccessible :  raw.githubusercontent.com

**Comment by Alexdara** [comment]
> It's because this address is inaccessible : raw.githubusercontent.com

When I enter the url raw.githubusercontent.com in chrome, it jump to github.com which shows my personal page.
Then how you fix it?

**Comment by sharpwood** [comment]
hosts

**Comment by Alexdara** [comment]
For my solution:
Open https://raw.githubusercontent.com/Redth/dotnet-maui-check/main/manifests/maui.manifest.json in chorme,
Save the html page as  maui.manifest.json.
Then use command: maui-check -m maui.manifest.json.
And it works.

**Comment by tanshanli** [comment]
可能是DNS污染，可以在C:\Windows\System32\drivers\etc，host文件中配置
`151.101.0.133 raw.githubusercontent.com`
确保ip能ping通，且不丢包，否则需要科学上网才能解决
