### ISSUE TITLE
Maui-check : Continue running gitlab-ci pipeline even with some errors

### ISSUE THREAD

**Issue by NemuelLealPereira** [Redth/dotnet-maui-check#121]
Hello @Redth, hello everyone,

I'm creating a pipeline inside gitlab. My job fails because there are some errors in the maui-check step.

Therefore, I would like to know if there is an argument that ignores any error that occurs with the maui-check command.

If there was **--ignore-error** argument to maui-check command, for example "maui-check --ci --non-interactive --fix **--ignore-error**", the maui-check step would be performed successfully and the next step would be performed.

thanks for your help

**Comment by Redth** [comment]
--skip the steps you want to ignore that are failing. 

Check out the readme for more info.
