### ISSUE TITLE
Can't work on Windows 7 SP1

### ISSUE THREAD

**Issue by taozuhong** [Redth/dotnet-maui-check#14]
Install: `dotnet tool install -g redth.net.maui.check` Run: `maui-check`  on Windows 7 SP1,

Just flash the black window, then nothing in all, no message output.

**Comment by timvandenhof** [comment]
Windows 7 is end-of-life and no longer supported by Microsoft for over a year now. So I doubt this tool is tested and supported on Windows 7 by it's author...

See the following statement from Microsoft about Windows 7 EOL on 14 jan 2020:
> Microsoft made a commitment to provide 10 years of product support for Windows 7 when it was released on October 22, 2009. This 10-year period has now ended, and Microsoft has discontinued Windows 7 support so that we can focus our investment on supporting newer technologies and great new experiences. The specific end of support day for Windows 7 was January 14, 2020. Technical assistance and software updates from Windows Update that help protect your PC are no longer available for the product. Microsoft strongly recommends that you move to Windows 10 to avoid a situation where you need service or support that is no longer available.

Source: https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962

**Comment by taozuhong** [comment]
Windows 7 EOL on 14 Jan 2020, that's Microsoft's business plan, but up to 20% of Windows market share is Windows 7, they should be supported.

**Comment by Redth** [comment]
I can't speak to dotnet actually being supported here, but we will not support using Windows 7 as a development machine for .NET MAUI apps.
