### ISSUE TITLE
Require JDK 11 for Android

### ISSUE THREAD

**Issue by jonathanpeppers** [Redth/dotnet-maui-check#20]
We are dropping support for the old JDK 1.8 in `C:\Program Files\Android\jdk\microsoft_dist_openjdk_1.8.0.25`. In .NET 6 Preview 4, the Android workload will no longer locate it by default, but you can still set it to `%JAVA_HOME%` or `/p:JavaSdkDirectory` manually.

We should prompt for users to install this new JDK 11 distro instead:

https://www.microsoft.com/openjdk

We can go ahead and start requiring this in `maui-check`, I think. `Boots.Core` seems like it could install these automatically.

**Comment by Redth** [comment]
The current --dev feed requires and installs OpenJDK11.
