### ISSUE TITLE
The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by qcjxberin** [Redth/dotnet-maui-check#27]
![image](https://user-images.githubusercontent.com/5792218/118060816-3a6c3a80-b3c6-11eb-85e8-c99ad6aa44c1.png)

**Comment by xiaokun** [comment]
@qcjxberin 
我遇到了同样的问题，调试后发现 Inner Exception 是：远程主机强迫关闭了一个现有的连接。主要原因是 https://raw.githubusercontent.com/Redth/dotnet-maui-check/main/manifests/maui-preview.manifest.json 这个文件获取失败。
解决办法是上VPN。

**Comment by HeinA** [comment]
I have this too. Visual Studio 2022 Preview on Windows Server 2022 preview.
Is there a solution?

**Comment by albertwoo** [comment]
You can just download https://raw.githubusercontent.com/Redth/dotnet-maui-check/main/manifests/maui.manifest.json locally and then use:  
```
maui-check -m your-downloaded-file
```

**Comment by albertwoo** [comment]
You can download two files
file1: https://raw.githubusercontent.com/Redth/dotnet-maui-check/main/manifests/maui.manifest.json
file2: https://raw.githubusercontent.com/dotnet/maui/release/6.0.1xx-preview5/eng/Versions.props
Replace `https://raw.githubusercontent.com/dotnet/maui/release/6.0.1xx-preview5/eng/Versions.props` in file1 with the local file path of file2.
```
maui-check -m file1
```

**Comment by Digisaman** [comment]
Tanx @albertwoo Worked for me

**Comment by HeinA** [comment]
Thank you very much @albertwoo

**Comment by Mr-Reid** [comment]
Thank you
