### ISSUE TITLE
Cant find Maui-check after installing

### ISSUE THREAD

**Issue by iMonZ** [Redth/dotnet-maui-check#30]
I'm unable to find or execute maui-check.

OP: macOS BigSur 11.4

As a default I am using the fish shell:

> You can invoke the tool using the following command: maui-check
> Tool 'redth.net.maui.check' (version '0.4.2') was successfully installed.

>  ~/Downloads  maui-check                                                        31s  Thu May 20 11:14:57 2021
> fish: Unknown command: maui-check

After that I have tried the same thing instead with the zsh shell:

> mvg@maxs-bigmac Downloads % dotnet tool uninstall -g Redth.Net.Maui.Check
> Tool 'redth.net.maui.check' (version '0.4.2') was successfully uninstalled.

> mvg@maxs-bigmac Downloads % dotnet tool install -g Redth.Net.Maui.Check
> You can invoke the tool using the following command: maui-check
> Tool 'redth.net.maui.check' (version '0.4.2') was successfully installed.

> mvg@maxs-bigmac Downloads % maui-check
> zsh: command not found: maui-check

I have installed the SDK: 3.1.408, 5.0.202 and 6.0.100-preview.4.21226.14 over Visual Studio

**Comment by Redth** [comment]
If you're just using the default location, they should end up here on macOS: `$HOME/.dotnet/tools`

You likely do not have this on your `PATH` environment variable.

https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools#install-a-global-tool
