### ISSUE TITLE
Allow option to tell the tool to not install the things for Mobile if they only want to use MAUI for Desktop apps.

### ISSUE THREAD

**Issue by AraHaan** [Redth/dotnet-maui-check#39]
I would like an option to tell the tool to not try to check or even install things for mobile like the Android SDK, or even the iOS bits if I want to only target for Desktop ones.

This is for cases where they want to have a minimal install of MAUI and never plan to make apps for Mobile devices.

**Comment by Redth** [comment]
You can use `--skip androidsdk --skip openjdk --skip androidemulator --skip xcode` etc... basically you can skip anything that's listed in `maui-check list` output.
