### ISSUE TITLE
The command `dotnet tool install -g Redth.Net.Maui.Check` causes the screen to reboot without responding.

### ISSUE THREAD

**Issue by huideyeren** [Redth/dotnet-maui-check#40]
When I run `dotnet tool install -g Redth.Net.Maui.Check` from the command line, my PC freezes and reboots.

The OS is Windows Insider Preview Build 21387 and the version of dotnet is `6.0.100-preview.4.21255.9`.
Visual Studio 2019 v16.11 Preview 1 is also installed on that PC. 

Note that I tried to install other tools installed with `dotnet tool install -g`, but the same event occurs with `dotnet-fsharplint`.

**Comment by Redth** [comment]
This sounds really odd.  Can you run something like `maui-check --verbose > mauicheck.log` and see what's in the logfile after?

**Comment by huideyeren** [comment]
Nothing was recorded in the log, but I found the cause.
I terminated the resident anti-virus software and was able to install it successfully.
