### ISSUE TITLE
Skip Windows check on macOS

### ISSUE THREAD

**Issue by davidortinau** [Redth/dotnet-maui-check#5]
When running on macOS, please don't bother trying to install Windows things. Perhaps just note that they were skipped.

I ran `maui-check --dev` and it tried to validate and install Microsoft.iOS.Windows.SDK.

**Comment by Redth** [comment]
tl;dr: Yes.

Long answer tl;dr: It's complicated.

We need to address an issue with how the iOS Windows SDK is associated to the ios workload manifest.  Until then I'm installing this pack outside of the workload, and there's no mechanism right now in maui-check to do that right now (which I'll add in the meantime).

It wouldn't harm anything to have it installed, but yes, it should not try.

**Comment by Redth** [comment]
Fixed in 0.3.0
