### ISSUE TITLE
Maui check failed to update

### ISSUE THREAD

**Issue by AhmedHemdan21** [Redth/dotnet-maui-check#51]
After updating to .NET 6 preview 5 I tried to run maui-check command and it showed `

> Updating to version 0.5.6 or newer is required:

` dotnet tool update --global Redth.Net.Maui.Check`, then when I run the update command I get this error 

> Tool 'redth.net.maui.check' failed to update due to the following:
Failed to uninstall tool package 'redth.net.maui.check': Access to the path 'C:\Users\Ahmed\\.dotnet\tools\.store\redth.net.maui.check\0.4.2' is denied.

Also, I tried to run ` dotnet tool uninstall --global Redth.Net.Maui.Check` but I get the same error.

**Comment by elOG8** [comment]
I have the same problem.... any news?

**Comment by Fabi** [comment]
Worked for me when I run it as admin 🤔

**Comment by AhmedHemdan21** [comment]
> Worked for me when I run it as admin 🤔

I tried with admin privilege using Windows Terminal, Command Prompt, and PowerShell and I get the same issue.
@Fabi did you have a previous version installed or is this a fresh install?

**Comment by ncarandini** [comment]
Please try to close any istance of VS Code or VS that may use the folder. Worst case scenario, reboot 😄 
I solved closing all istances of VS Code.

**Comment by AhmedHemdan21** [comment]
> Please try to close any instance of VS Code or VS that may use the folder. Worst case scenario, reboot 😄
> I solved closing all instances of VS Code.
> I found it when I tried to delete the folder by myself from the file Explorer. It refused to delete it telling me that it was used by someone...

Thanks for your suggestion, I tried everything from restarting the device (around 9 times), trying to uninstall .NET SDK which was a total nightmare to do so. Finally, deleting the SDK files manually and repairing VS 2022 did solve the issue, so it seems that installing VS 2022 with .NET SDK at the same time caused lots of issues.
