### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by realivanjx** [Redth/dotnet-maui-check#52]
It seems that maui workloads is breaking my visual studio installation. This happens after i installed dotnet 6 preview 5. My other computer is just fine after i installed the preview 5 without maui workloads installed. Projects wont load (even non maui projects like blazor, wpf, asp net core, etc) with this error:
`error  : The project file cannot be opened. The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not find file 'C:\Program Files\dotnet\sdk-manifests\6.0.100\Microsoft.NET.Workload.Android\WorkloadManifest.json'.`
When i tried to update the tool i got this:
```
 dotnet tool update --global Redth.Net.Maui.Check

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.100-preview.5.21302.13

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
C:\Users\t\AppData\Local\Temp\vcwbd54v.uva\restore.csproj(5,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not find file 'C:\Program Files\dotnet\sdk-manifests\6.0.100\Microsoft.NET.Workload.Android\WorkloadManifest.json'.
C:\Program Files\dotnet\sdk\6.0.100-preview.5.21302.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.props(14,3): warning MSB4243: The NuGet-based SDK resolver failed to run because NuGet assemblies could not be located.  Check your installation of MSBuild or set the environment variable "MSBUILD_NUGET_PATH" to the folder that contains the required NuGet assemblies. Could not find file 'C:\Program Files\dotnet\sdk-manifests\6.0.100\Microsoft.NET.Workload.Android\WorkloadManifest.json'.
C:\Program Files\dotnet\sdk\6.0.100-preview.5.21302.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.props(14,38): error MSB4236: The SDK 'Microsoft.NET.SDK.WorkloadAutoImportPropsLocator' specified could not be found. [C:\Users\t\AppData\Local\Temp\vcwbd54v.uva\restore.csproj]
Tool 'redth.net.maui.check' failed to update due to the following:
The tool package could not be restored.
Tool 'redth.net.maui.check' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```
Tried to repair my visual studio via the installer with no luck. Is there anything else i can do? Otherwise i have to fully reinstall my visual studio installation. Any help is appreciated. Thanks.

**Comment by czirok** [comment]
I found a workaround.

I deleted all *preview* files and folders in the "\Program Files\dotnet \*" folder.

IMPORTANT! Only the *preview* files and folders!

Then, "dotnet new" and all "dotnet *" and "dotnet tool install -g Redth.Net.Maui.Check" command worked again.

**Comment by realivanjx** [comment]
thanks for the tips. however i have reinstalled my entire visual studio installation before i was able to try out your tips. hopefully it will be helpful for anybody else facing the same issue.

**Comment by LostBeard** [comment]
Yay! Working around Microsoft's incompetence is becoming a daily routine. Kind of like when Windows wants to force shutdown apps you are in the middle of typing into because it wants to install more buggy, untested updates. Such fun.

**Comment by cr1pto** [comment]
I ran into this issue today as well and doing @Stamo-Gochev's suggestion worked for me.
