### ISSUE TITLE
The maui-check tool is not signed by a trusted publisher

### ISSUE THREAD

**Issue by SvetBonev** [Redth/dotnet-maui-check#65]
The maui-check tool requires elevation to fix issues.
The elevation prompt, however, shows that the tool is not signed by a trusted publisher.

![IMG_1808](https://user-images.githubusercontent.com/46607019/124322732-d435a580-db34-11eb-8893-8333cf035f82.png)

**Comment by Redth** [comment]
I did add a signature in recent versions, however it seems the signed shim isn't always replaced, or something happens where if you do a `dotnet tool update` (as opposed to a `dotnet tool uninstall` and then `dotnet tool install`, the signature is no longer detected. 

I have filed a bug https://github.com/dotnet/sdk/issues/19663 with this info.
