### ISSUE TITLE
Add WebView2 check

### ISSUE THREAD

**Issue by Eilon** [Redth/dotnet-maui-check#66]
I sent a PR to update the MAUI installation docs regarding this: https://github.com/dotnet/docs-maui/pull/48

But if maui-check could make sure WebView2 is installed, that would be even better.

**Comment by Eilon** [comment]
Here's the doc from WebView about how to detect and/or install WebView2: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#online-only-deployment

**Comment by Eilon** [comment]
I logged a separate issue to track adding an option to install WebView2: #68

**Comment by jonathanpeppers** [comment]
@Redth @Eilon is there a switch to disable this check? I think it causes failures in CI scenarios:

https://dev.azure.com/dnceng/public/_build/results?buildId=1239230&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=ac0b0b0f-051f-52f7-8fb3-a7e384b0dde9&l=188

For now, I think I can ignore the exit code or something.

**Comment by Redth** [comment]
@jonathanpeppers  ‘—skip edgewebview2’

**Comment by jonathanpeppers** [comment]
Yeah `--skip edgewebview2` works: https://github.com/dotnet/maui-samples/pull/183
