### ISSUE TITLE
Add WebView2 installation option to the check

### ISSUE THREAD

**Issue by Eilon** [Redth/dotnet-maui-check#68]
In issue #66 (PR: #67) the idea was to _check_ if WebView2 is installed, and if not, provide a link to install it.

Ideally there would be an option to install it by downloading the installer and running it.

Here's the doc from WebView about how to detect and/or install WebView2: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#online-only-deployment

**Comment by Redth** [comment]
Thanks! in 0.6.1

**Comment by Eilon** [comment]
Oh wait @Redth did you add logic to _install_ WebView2? The PR I sent was just for checking and asking the user to install.

**Comment by Redth** [comment]
Not yet :)

**Comment by Eilon** [comment]
Ah OK then this issue should remain open. This one is about actually downloading and installing it. Issue https://github.com/Redth/dotnet-maui-check/issues/66 was about just detecting and informing.
