### ISSUE TITLE
[Bug] `maui-check` fails to install workloads, but thinks it installed them

### ISSUE THREAD

**Issue by mattkenefick** [Redth/dotnet-maui-check#78]
Windows 11 Pro (10.0.22000 Build 22000)
dotnet 6.0.100-preview.6.21355.2
Visual Studio 2022 Preview

1. The first time I ran `maui-check`, it failed to install all of the workloads.
2. I ran it again, and it said it successfully found them.
3. I attempted to build a maui project in visual studio and was told that my workloads were **not** installed. 
4. I tried running `dotnet workload install maui-core` and was told I needed to elevate my permissions to install them.

Everything was fine after launching Terminal as administrator and manually installing the cores, but I'm not sure why `maui-check` thought it worked when it didn't. I'm assuming maybe it generated some folders, but not the core files required.

**Comment by premingiet** [comment]
Try to run this command in elevated command prompt ```run command prompt as Administrator ```
```cmd
dotnet workload install maui
```
also run this command after that
```cmd
dotnet new -i Microsoft.Maui.Templates
```

**Comment by mattkenefick** [comment]
@premingiet As mentioned, I was able to do that.

The purpose of this ticket is that `maui-check` *thought* it was successful even after it wasn't.

**Comment by Redth** [comment]
Please try the latest version of maui-check with preview7, it should do a better job of getting things setup now that it is only using dotnet workload commands.
