### ISSUE TITLE
 Android Emulator Checkup -  Unable to find any Android Emulators

### ISSUE THREAD

**Issue by SundaramSubramanian** [Redth/dotnet-maui-check#79]
While checking - maui-check command,  I am getting this error. 

![image](https://user-images.githubusercontent.com/65156588/127010377-a31cff62-5544-4134-94a6-d4f31519eac3.png)

I am using VS 2022, and when checking Tools->Andriod-> SDK , I can see that Emulator is installed. What I am missing here?. 

![image](https://user-images.githubusercontent.com/65156588/127011074-7ed12c70-79f7-474a-a4b2-a5fc5c33bed6.png)

**Comment by peridot9** [comment]
I think you have to create at least a android virtual device using Android Device Manager in Visual Studio.
"Android Emulator checkup" section does not check Android Emulator itself. 
This description in maui-check is misleading.
Refer to my screenshot.
Also, you should install webview2.
![20210802-maui-check-emucheck](https://user-images.githubusercontent.com/38744638/127845041-d8a42968-d797-4523-bc80-aac31b6e516e.png)

**Comment by Redth** [comment]
The latest version of maui-check has some fixes for android emulators, please try updating and log a new issue if you still find problems.
