### ISSUE TITLE
Xcode check fails

### ISSUE THREAD

**Issue by matkoch** [Redth/dotnet-maui-check#87]
Manifest defines:

```
    "xcode": {
      "minimumVersion": "13.0"
    },
```

But during execution on GitHub Actions (macOS) it shows:

<img width="255" alt="image" src="https://user-images.githubusercontent.com/5005566/127792726-7d2854c7-7e04-45a3-bb2b-6d6f4c1e6e15.png">

**Comment by matkoch** [comment]
I guess according to the list of [virtual environments](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode), version 13 is not preinstalled, and afaik, there is also no way to fix this manually. Do you have any recommendations, which CI service can already be used to build Maui apps ?

**Comment by Redth** [comment]
Sorry, we don't control GitHub Actions' virtual environments.  You'll have to find a way to provision the required xcode version yourself if you want to use it in CI there.

**Comment by matkoch** [comment]
@Redth I understand that you can't control that, but afaic this is still a bug because the check succeeds without any error or warning.

**Comment by Redth** [comment]
It doesn't now in the latest version, it checks the Xcode build and errors.
