### ISSUE TITLE
Failed to find Android SDK.

### ISSUE THREAD

**Issue by touzas** [Redth/dotnet-maui-check#9]
Hi,

When i tried to run application i have this error: Failed to find Android SDK.

In my case to solve this i change a AndroidSdkCheckup.cs
`var defaultPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86), "Android", "android-sdk");
var sdkInstance = installer.FindInstance(defaultPath);`

Regards

**Comment by Redth** [comment]
Can you try 0.3.1 please?  This should help locate the sdk.

**Comment by touzas** [comment]
I try a 0.3.2 and this rules OK.
Thanks
