### ISSUE TITLE
Visual Studio 2022 Preview 2 detection issue

### ISSUE THREAD

**Issue by matko238** [Redth/dotnet-maui-check#92]
Trying with latest VS2022 preview... 

Microsoft Visual Studio Enterprise 2022 Preview (64-bit)
Version 17.0.0 Preview 2.1
`
Tool 'redth.net.maui.check' (version '0.7.2') was successfully installed.`
`
maui-check --dev`

OpenJDK 11.0 Checkup...
16.0.1 (C:\Program Files\Microsoft\jdk-16.0.1.9-hotspot\bin\..)
1.8.0-25 (C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25)
11.0.11 (C:\Program Files\Microsoft\jdk-11.0.11.9-hotspot\bin\..)

Visual Studio 17.0.0-pre.3.0 Checkup...
17.0.0-pre.2.1
16.11.0-pre.3.0
Missing Visual Studio >= 17.0.0-pre.3.0

But latest available version is 17.0.0-pre2.1? VS check for update says that is the last one.
![image](https://user-images.githubusercontent.com/8600698/128571695-705e52b9-cd34-4393-8a98-19f851715104.png)

**Comment by fuocor** [comment]
Same here...

**Comment by kfechter** [comment]
Preview 3 wasn't out until yesterday, however due to an installer issue, it has temporarily been pulled. Once that update is released again, it should fix the above issue. 

https://devblogs.microsoft.com/visualstudio/visual-studio-2022-preview-3-now-available/

**Comment by Redth** [comment]
^ also, it's safe to skip the error using `--skip vswin` the warning for CLI development in the meantime.
