### ISSUE TITLE
This version of the tool is incompatible with installing an older version of .NET 6

### ISSUE THREAD

**Issue by SundayRX** [Redth/dotnet-maui-check#93]
I have installed the latest development kit .NET6.0
However, the tool still prompts for incompatibility with older versions. NET 6.0
By the way even though I uninstall the .NET 6.0 the tool still prompts an error  
I'm so confused that someone can help me?

PS C:\Users\SundayRX> dotnet sdk check
.NET SDKs:
Version                        Status
------------------------------------------
5.0.302                        Up to date.
6.0.100-preview.6.21355.2      Up to date.

.NET Runtimes:
Name                              Version                       Status
-----------------------------------------------------------------------------------------
Microsoft.AspNetCore.All          2.1.28                        Up to date.
Microsoft.AspNetCore.App          2.1.28                        Up to date.
Microsoft.NETCore.App             2.1.28                        Up to date.
Microsoft.AspNetCore.App          3.1.17                        Up to date.
Microsoft.NETCore.App             3.1.17                        Up to date.
Microsoft.WindowsDesktop.App      3.1.17                        Up to date.
Microsoft.NETCore.App             5.0.2                         Patch 5.0.8 is available.
Microsoft.WindowsDesktop.App      5.0.2                         Patch 5.0.8 is available.
Microsoft.AspNetCore.App          5.0.8                         Up to date.
Microsoft.NETCore.App             5.0.8                         Up to date.
Microsoft.WindowsDesktop.App      5.0.8                         Up to date.
Microsoft.NETCore.App             6.0.0-preview.6.21352.12      Up to date.
Microsoft.WindowsDesktop.App      6.0.0-preview.6.21353.1       Up to date.
Microsoft.AspNetCore.App          6.0.0-preview.6.21355.2       Up to date.

The latest versions of .NET can be installed from https://aka.ms/dotnet-core-download. For more information about .NET lifecycles, see https://aka.ms/dotnet-core-support.

PS C:\Users\SundayRX> maui-check
      _   _   _____   _____     __  __      _      _   _   ___
     | \ | | | ____| |_   _|   |  \/  |    / \    | | | | |_ _|
     |  \| | |  _|     | |     | |\/| |   / _ \   | | | |  | |
  _  | |\  | | |___    | |     | |  | |  / ___ \  | |_| |  | |
 (_) |_| \_| |_____|   |_|     |_|  |_| /_/   \_\  \___/  |___|

¤ .NET MAUI Check v0.7.2.0 ¤
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────This tool will attempt to evaluate your .NET MAUI development environment.
If problems are detected, this tool may offer the option to try and fix them for you, or suggest a way to fix them
yourself.

Thanks for choosing .NET MAUI!
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────? Synchronizing configuration...
× This version of the tool is incompatible with installing an older version of .NET 6

Press enter to exit...

**Comment by jepperaskdk** [comment]
Same here,
dotnet --version
6.0.100-preview.6.21355.2

Tool 'redth.net.maui.check' (version '0.7.2') was successfully installed.

**Comment by ziaulhasanhamim** [comment]
I'm also facing the same issue with .net 6 preview 6

**Comment by mwettste** [comment]
I had the same issue. When i run the tool with "maui-check --dev" it somehow gets past that stage but then displays the following warning "Missing Visual Studio >= 17.0.0-pre.3.0".
It still continues but then later fails to install the .NET SDK Workloads for iOS android-aot and several others.
Could it be that version 0.7.2 of the maui-check already checks for a newer version of the tools that are currently released? For example as of the time of writing this, only VS 17.0.0-pre.2.1 is released, as far as I can see.

**Comment by MutatePat** [comment]
I can report the same issue. Just like @mwettste I can skip the initial error-message using the dev argument.

**Comment by marqdouj** [comment]
Reset my PC this morning and installed all the latest versions, etc.
Ran maui-check and get the same error.

**Comment by chrisheil** [comment]
It looks like the maui-check tool is checking for the dotnet sdk v6 preview 7, which is not released yet. The question then is whether this is a mistake and it should be updated to preview 6? Or is this version of maui-check is actually intended for preview 7 and just released too early?

https://github.com/Redth/dotnet-maui-check/blob/0bc3b3985fe498f1836e778a44411a691c1a81d1/MauiCheck/ToolInfo.cs#L69

**Comment by DoubleLee** [comment]
![image](https://user-images.githubusercontent.com/4467783/128641432-19e5a411-03d1-4cf4-9ca5-0db5fed40408.png)
It's offering to download preview 7

**Comment by DoubleLee** [comment]
![image](https://user-images.githubusercontent.com/4467783/128642038-0dc6a901-0351-4bd3-8ed2-4c1d8a6016f8.png)

**Comment by MutatePat** [comment]
> ![image](https://user-images.githubusercontent.com/4467783/128641432-19e5a411-03d1-4cf4-9ca5-0db5fed40408.png)
> It's offering to download preview 7.
> I used the --dev command as mentioned earlier.
> 
> EDIT: breaks later though :(
> ![image](https://user-images.githubusercontent.com/4467783/128641584-377d96d8-7880-4546-bf71-875c08857368.png)

I did the same and updated to the P7 build and decided to ignore these errors( I wanted to test Blazor Desktop, not Mobile so I has no need for Android / IOS).

Unfortunately none of the nuget packages are updated for P7, so you can not launch anything with this install.

**Comment by kfechter** [comment]
I was able to successfully use maui-check (including installing preview 7). The only failure I get is the detection of Preview 3 of visual studio 2022 (which isn't out yet)

**Comment by bcd6** [comment]
I got same error as mentioned above when I just run maui-check.
It resolved after I run maui-check --preview

**Comment by johncclayton** [comment]
I uninstalled Visual Studio 2022 and manually uninstalled the rc1 .net 6 package.  I then tried maui-check - without args it complains with this error: "This version of the tool is incompatible with installing an older version of .NET 6".

Then I used the "--dev" argument; this has some success - but in the end also fails due to the following:

![image](https://user-images.githubusercontent.com/1405394/128696409-81abe180-60a3-4817-bc4f-0c9b8ca8ac2f.png)

Any help would be greatly appreciated and if there is something else I should provide I'm happy to do so.  Thank you!

**Comment by mwettste** [comment]
Thanks a lot @Toshik this resolved my issue!
Wasn't aware that you could easily install an older version.

**Comment by johncclayton** [comment]
I tried this and it worked! 

Thank you @Toshik - that's a very good hint.  

I had preview 7 installed, so the maui-check initially failed, but after manually removing that via the add/remove programs menu, maui-check then proceeded to install preview 6 (6.0.100, 6.21355.2).

One comment though; even though it appears everything installed - the tool complains that there was an error, as shown below.  I'll do some small checks afterwards or in the coming days.

![image](https://user-images.githubusercontent.com/1405394/128758452-5b62174a-3e0c-455a-8af0-ad7e0eccd089.png)

**Comment by Toshik** [comment]
> I tried this and it worked! 
> 
> 
> 
> Thank you @Toshik - that's a very good hint.  
> 
> 
> 
> I had preview 7 installed, so the maui-check initially failed, but after manually removing that via the add/remove programs menu, maui-check then proceeded to install preview 6 (6.0.100, 6.21355.2).
> 
> 
> 
> One comment though; even though it appears everything installed - the tool complains that there was an error, as shown below.  I'll do some small checks afterwards or in the coming days.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/1405394/128758452-5b62174a-3e0c-455a-8af0-ad7e0eccd089.png)
> 
> 
> 
> 

Looks like it can't detect VS2020 installed. Not sure if it is related to the issue discussed here, though.

**Comment by djinnet** [comment]
![image](https://user-images.githubusercontent.com/9974608/128907035-621f49d2-433d-4432-ba0d-3e2051e392f7.png)

I tried to run with v0.6.1 maui-check as suggested by Toshik.
I am using VS2022 with 6.0.100-preview.6.21355.2. I have tried to follow the MS docs, but I always hits "the maui-check wall". 
I would love to know if I am using the wrong .net or maui-check version?

Worth mention that I tried to run it again after the screenshot above, but I got an ``Error resolving type specified in JSON 'DotNetCheck.Manifest.NuGetFeedVariableMapper, MauiCheck'. Path 'check.variableMappers[0].$type', line 9, position 74.`` error. Not sure what is causing that error, but if that sounds like I should make another issue for that specified bug, let me know. 👍

**Comment by PaulAnderson02** [comment]
> ![image](https://user-images.githubusercontent.com/9974608/128907035-621f49d2-433d-4432-ba0d-3e2051e392f7.png)
> 
> I tried to run with v0.6.1 maui-check as suggested by Toshik.
> I am using VS2022 with 6.0.100-preview.6.21355.2. I have tried to follow the MS docs, but I always hits "the maui-check wall".
> I would love to know if I am using the wrong .net or maui-check version?
> 
> Worth mention that I tried to run it again after the screenshot above, but I got an `Error resolving type specified in JSON 'DotNetCheck.Manifest.NuGetFeedVariableMapper, MauiCheck'. Path 'check.variableMappers[0].$type', line 9, position 74.` error. Not sure what is causing that error, but if that sounds like I should make another issue for that specified bug, let me know. 👍

Me too getting the same error after I updated by VS2022 to the latest preview 3 release today

**Comment by Redth** [comment]
Also, please see the [Troubleshooting](https://github.com/Redth/dotnet-maui-check/blob/main/README.md#troubleshooting) section of the readme for more info.
