### ISSUE TITLE
Error resolving type specified in JSON 'DotNetCheck.Manifest.NuGetFeedVariableMapper, MauiCheck'

### ISSUE THREAD

**Issue by DevTati66** [Redth/dotnet-maui-check#96]
multiple issues around this issues occured during installation process of preview 7. All were at least about reading manifest information.
>> dotnet workload install maui - failed
- when reached Installation roll back failed: Failed to install manifest microsoft.net.sdk.android version 30.0.100-preview.7.93: The transaction has aborted.. Deinstallation started.
>> check-maui - also failed
Error: Error resolving type specified in JSON 'DotNetCheck.Manifest.NuGetFeedVariableMapper, MauiCheck'. Path 'check.variableMappers[0].$type', line 9, position 74.

Now deinstalled SKD 6 Preview7 and steped back to Preview6 and  nothing works anymore.
Any hints

**Comment by Redth** [comment]
Yes, please update your tool version: `dotnet tool update -g redth.net.maui.check`

**Comment by Redth** [comment]
`maui-check` will now install Preview 7 and Preview 6 is no longer supported to install via maui-check.

You can try a few things if you are having problems with preview7 installation: https://github.com/Redth/dotnet-maui-check/blob/main/README.md#troubleshooting
